# Generated by Django 2.1.7 on 2019-02-19 16:35

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('a11', models.FloatField(default=0)),
                ('a12', models.FloatField(default=0)),
                ('a21', models.FloatField(default=0)),
                ('a22', models.FloatField(default=0)),
                ('a31', models.FloatField(default=0)),
                ('a32', models.FloatField(default=0)),
                ('state', models.CharField(default='\\(\\beta_{1}\\)', max_length=20)),
                ('threshold', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('exclude_alpha1', models.BooleanField(default=False)),
                ('exclude_alpha2', models.BooleanField(default=False)),
                ('exclude_alpha3', models.BooleanField(default=False)),
                ('losses', models.FloatField(default=0)),
                ('answer_nrand', picklefield.fields.PickledObjectField(default=list, editable=False)),
                ('answer_rand', picklefield.fields.PickledObjectField(default=list, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='MatrixRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('a2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix', to='tutorial.Matrix')),
            ],
        ),
    ]
