# Generated by Django 2.1.7 on 2019-09-28 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('controlled_state', models.CharField(choices=[('0', 'beta_{1}'), ('1', 'beta_{2}')], max_length=10)),
                ('threshold', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a0', models.FloatField()),
                ('a1', models.FloatField()),
                ('excluded', models.BooleanField(default=False)),
                ('is_answer', models.BooleanField(default=False)),
                ('message', models.CharField(default='', max_length=20)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix', to='tutorial.Matrix')),
            ],
        ),
    ]
